version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test-build-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install Dependencies
                command: npm install
            - save_cache:
                key: v1-npm-deps-{{ checksum "package-lock.json" }}
                paths:
                  - ./node_modules
            - run:
                name: Run Tests
                command: npm test
            - run:
                name: Build
                command: npm run build
            - run:
                name: Install Firebase Tools
                command: npm install --prefix=./firebase-deploy firebase-tools
            - run:
                name: Deploy to Firebase
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  test-build-deploy:
    jobs:
      - test-build-deploy
