version: 2.1
orbs:
  node: circleci/node@1.1.6
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: deploy
workflows:
  build-and-test:
    jobs:
      - build-and-test
