version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - checkout
            - restore_cache:
                keys:
                  # Find a cache corresponding to this specific package-lock.json
                  - v1-npm-deps-{{ checksum "package-lock.json" }}
                  # Fallback cache to be used
                  - v1-npm-deps-
            - run:
                name: Install Dependencies
                command: npm install
            - save_cache:
                key: v1-npm-deps-{{ checksum "package-lock.json" }}
                paths:
                  - ./node_modules
            - run:
                name: React Build
                command: npm run build
            - run:
                name: Firebase Deploy
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
workflows:
  build-and-test:
    jobs:
      - build-and-test
